INSERT IGNORE INTO roles(name) VALUES('ROLE_ADMIN');
INSERT IGNORE INTO roles(name) VALUES('ROLE_QA');
INSERT IGNORE INTO roles(name) VALUES('ROLE_PM');
INSERT IGNORE INTO roles(name) VALUES('ROLE_DEVELOPER');
INSERT IGNORE INTO roles(name) VALUES('ROLE_HR');
INSERT IGNORE INTO roles(name) VALUES('ROLE_PRODUCT_ADMIN');
INSERT IGNORE INTO roles(name) VALUES('ROLE_TECH_LEAD');
    